use_frameworks!

target 'MBTextFieldWithInputValidator_Example' do
  pod 'MBTextFieldWithInputValidator'
end

target 'MBTextFieldWithInputValidator_Tests' do
  pod 'MBTextFieldWithInputValidator'

  
end
